FROM registry.access.redhat.com/rhscl/httpd-24-rhel7

MAINTAINER tjkim <iljine@pentalink.com>


RUN   yum install -y --disableplugin=subscription-manager httpd && \ 
      yum clean all --disableplugin=subscription-manager -y

# Run as the 1001 user
USER 1001

# Launch httpd
CMD service httpd start 

