FROM registry.access.redhat.com/ubi8/ubi:latest 

MAINTAINER tjkim <iljine@pentalink.com>
USER root

RUN   yum install -y --nodocs --disableplugin=subscription-manager httpd && \ 
      yum clean all --disableplugin=subscription-manager -y

# Launch httpd
RUN service httpd start 

# Run as the 1001 user
USER 1001